[package]
name = "mongodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"

futures = "0.3.28"

[dependencies.mongodb]
version = "2.8.2"
features = ["tokio-runtime"]
